version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - echo Installing Docker...
      - yum update -y
      - yum install awscli docker -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 140023392580.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=545009851622.dkr.ecr.us-east-1.amazonaws.com/yuva
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t poc .
      - docker tag poc:latest 545009851622.dkr.ecr.us-east-1.amazonaws.com/yuva:latest
      # - docker tag poc:$IMAGE_TAG 140023392580.dkr.ecr.ap-south-1.amazonaws.com/poc:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 545009851622.dkr.ecr.us-east-1.amazonaws.com/yuva:latest
      - echo Writing image definitions file...
      - printf '[{"name":"poc","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
